# site settings
title: The Door Church of Maricopa
subtitle: 
email: info@thedoormaricopa.com
description: The Door Church is a local church in Maricopa
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://doormaricopa.github.io" # the base hostname & protocol for your site
author:
phone: (520) 701-1223

# social settings
500px_url:
facebook_url:
github_url: 
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

future: true

sass:
  style: compressed

collections:
  about:
    output: true
    permalink: /:collection/:slug
  events:
    output: true
    permalink: /:collection/:name
  featured:
    output: true
  info:
    output: true